### ISSUE TITLE
TODOs for Release 1.0.0

### ISSUE THREAD

**Issue by luca28pet** [PocketWarriors/SkywarsPe#3]
Here is a todo list:

- [x] Add basics functions
      * [x] Timer
      * [x] Commands
      * [x] Spawn system
- [x] Re-Write plugin.yml
      * [x] Reorganize permissions
      * [x] Register command properly
- [x] Killing and death saving, with ranks and money
- [ ] Kits in-game
- [x] Sign system
- [ ] Multi-arena support
- [ ] World saving and restoring
- [ ] ...maybe something else...

**Comment by WYH233** [comment]
but where's the map?

**Comment by ghost** [comment]
can u please add chest resetting support?

**Comment by ghost** [comment]
can u please add chest resetting support?

**Comment by luca28pet** [comment]
the project is dead. rip.

**Comment by AndreyNazarchuk** [comment]
This is actually the base for my plugin, though I now have almost 3000
lines over 4 files. If the author wants I can upload it to this repo.
